// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mapping_Strategy_TPT.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    partial class ApplicationDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.HasBaseType("User");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BirthDate = new DateTime(2003, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sardor Sohinazarov",
                            PhoneNumber = "998912040618",
                            EnrollmentDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Dasturiy injinering",
                            StudentNumber = "S54321"
                        },
                        new
                        {
                            Id = 2L,
                            BirthDate = new DateTime(2010, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sarvarbek Sohinazarov",
                            PhoneNumber = "998912040619",
                            EnrollmentDate = new DateTime(2027, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Siyosat",
                            StudentNumber = "S67890"
                        },
                        new
                        {
                            Id = 3L,
                            BirthDate = new DateTime(2002, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sanjarbek Sohinazarov",
                            PhoneNumber = "998912040620",
                            EnrollmentDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Iqtisodiyot",
                            StudentNumber = "S98765"
                        });
                });

            modelBuilder.Entity("Teacher", b =>
                {
                    b.HasBaseType("User");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 4L,
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Valiyev Inomjon",
                            PhoneNumber = "998903440723",
                            Subject = "Matematika"
                        },
                        new
                        {
                            Id = 5L,
                            BirthDate = new DateTime(1980, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nazirov Shuxratjon",
                            PhoneNumber = "998912047322",
                            Subject = "Fizika"
                        });
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.HasOne("User", null)
                        .WithOne()
                        .HasForeignKey("Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Teacher", b =>
                {
                    b.HasOne("User", null)
                        .WithOne()
                        .HasForeignKey("Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
